### ISSUE TITLE
Issue with test 

### ISSUE THREAD

**Issue by anissalopez** [learn-co-curriculum/phase-1-first-class-functions-lab#17]
### Canvas Link

https://learning.flatironschool.com/courses/6548/assignments/237480?module_item_id=557732

### Concern

The test below createFareMultiplier asks us to create a function that will quadruple the fare. However, the test code file is testing the number 5 and it is testing to see if the function returns 25. Which is not quadrupling the fare. 

 `createFareMultiplier()` — This is a higher-order function that takes in one
  argument, an integer, and returns a function that will multiply a fare for a
  ride accordingly. For example, if `createFareMultiplier()` receives an argument
  of `4`, it will return a function that takes in a fare as an argument and
  quadruples the fare.

**Comment by Matt-Eva** [comment]
Hey @anissalopez 

It looks like the test file is actually creating a fare _quintupler_ not a fare _quadrupler_. So the test is actually valid! But thank you for contributing to our curriculum! We appreciate student feedback.

Matt
