### ISSUE TITLE
Readme clarification

### ISSUE THREAD

**Issue by dexterfitch** [learn-co-curriculum/phase-1-first-class-functions-lab#4]
# Link to Canvas

> [https://learning.flatironschool.com/courses/4376/assignments/135201?module_item_id=280863](https://learning.flatironschool.com/courses/4376/assignments/135201?module_item_id=280863)

## What should be changed?

Original:
> `returnFirstTwoDrivers()` — Declare a variable with const that is assigned an anonymous function. The assigned function should accept an array of drivers as an argument and return the first two drivers in the array.

Recommended:
`returnFirstTwoDrivers()` — Declare the variable `returnFirstTwoDrivers` with `const` and assign to it an anonymous function. The assigned function should accept an array of drivers as an argument and return the first two drivers in the array.

## Additional context

> Several students today asked for clarification on the wording, so I thought I'd provide some!

**Comment by lizbur10** [comment]
Thanks @dexterfitch ! This change has been made 💙
