### ISSUE TITLE
Typo/Bug

### ISSUE THREAD

**Issue by NJustin517** [learn-co-curriculum/phase-1-first-class-functions-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/4565/assignments/160555?module_item_id=344240

### Concern

I believe I encountered a bug/typo in the First-Class Functions Lab.  In the indexTest.js file, it declares the drivers variable as ['Antonia', 'Nuru', 'Amari', 'Chelsea'], but it expects to return ['Antonia', 'Nuru', 'Amari', 'Mo'] when making sure it WASN'T changed by our code.  I changed the name Chelsea to Mo in the test file and that was the only way I could pass the tests.

### Suggested Changes

Change drivers variable to ['Antonia', 'Nuru', 'Amari', 'Mo']

**Comment by kanghamin** [comment]
Yeah I found this issue as well.

**Comment by graciemcguire** [comment]
Thanks for flagging this @NJustin517 and @kanghamin ! We've just fixed the test so all should be working now!
Thank you for contributing to the Flatiron curriculum!
