### ISSUE TITLE
Use different concept instead of `drivers` and preview of data structure

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/phase-1-first-class-functions-lab#9]
### Canvas Link

https://learning.flatironschool.com/courses/4617/assignments/160579?module_item_id=344380

### Concern

Can we clarify what is `driver` and what the array of drivers should look like?
> returnFirstTwoDrivers() — Declare the variable returnFirstTwoDrivers with const and assign an anonymous function to it. The assigned function should accept an array of drivers as an argument and return the first two drivers in the array.

### Suggested Changes

I have three suggestions for issues students are running into with this lab:

1. Use a different conceptual example instead `drivers`. A few of my students are confused what "drivers" means and not understanding that it is just a name of a person as a string.
>`returnFirstTwoNeighbors()` — Declare the variable `returnFirstTwoNeighbors` with `const` and assign an anonymous function to it. The assigned function should accept an array of the names of neighbors as an argument, and return the first two neighbors in the array.
2. Can we show students an example of what the expected array will look like, illustrating it is an array of strings:
>`const neighbors = ['Antonia', 'Nuru', 'Amari', 'Mo'];`
3. Use examples of what expected return should look like.
>`returnFirstTwoNeighbors()` — Declare the variable `returnFirstTwoNeighbors` with `const` and assign an anonymous function to it. The assigned function should accept an array of the names of neighbors as an argument, and return the first two neighbors in the array.
> ```
> returnFirstTwoNeighbors(['Antonia', 'Nuru', 'Amari', 'Mo'])
> // => (['Antonia', 'Nuru']
>```

**Comment by graciemcguire** [comment]
Hey @karsonkalt ! Sorry for the delay on this, the issue got lost in my notifications! I like the idea of changing the concept but if we were to change to `neighbors`, what would you suggest changing the tests on fares (`createFareMultiplier()`, `fareDoubler()`, etc) to, so they make sense for neighbors? 
Again sorry for the delay!

**Comment by lizbur10** [comment]
Hi @karsonkalt! Thanks for these suggestions. I didn't change the example for the reason @graciemcguire mentioned, but I incorporated your other suggestions (and a couple other things) to hopefully make this lab less confusing for students.

Thanks again! 💙
